import { Stack, StackProps, RemovalPolicy, Duration, CfnOutput } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import {
  Bucket,
  BucketEncryption,
  HttpMethods,
  BlockPublicAccess,
  StorageClass,
  ObjectOwnership,
} from 'aws-cdk-lib/aws-s3';
import {
  PolicyStatement,
  Effect,
  AnyPrincipal,
  User,
  ManagedPolicy,
} from 'aws-cdk-lib/aws-iam';
import type { EnvConfig } from '../config/env-config';

interface StorageStackProps extends StackProps {
  config: EnvConfig;
}

/**
 * Single S3 bucket with prefix-based separation.
 *
 * Layout:
 *   private/
 *     receipts/{orgId}/{employeeId}/{claimId}/{filename}
 *     employee-docs/{orgId}/{employeeId}/{filename}
 *     onboarding-docs/{orgId}/{instanceId}/{taskId}/{filename}
 *   public/
 *     branding/{orgId}/logo.png, favicon.ico, login-bg.jpg
 *   cache/
 *     payslips/{orgId}/{cycleId}/{employeeId}.pdf
 *
 * Access model:
 *   - Bucket-level Block Public ACLs is ON (no object ACLs allowed).
 *   - Block Public Bucket Policy is OFF so we can grant public read on `public/*` only.
 *   - Everything else is reachable only via presigned URLs generated by the API.
 *
 * Lifecycle:
 *   - private/* — keep current versions forever; old versions delete after 90 days.
 *   - cache/* — delete after 30 days (regenerated on demand).
 *   - public/* — no expiration.
 */
export class StorageStack extends Stack {
  public readonly bucket: Bucket;
  public readonly appUser: User;

  constructor(scope: Construct, id: string, props: StorageStackProps) {
    super(scope, id, props);

    const { config } = props;
    const removalPolicy =
      config.removalPolicy === 'retain' ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY;

    this.bucket = new Bucket(this, 'AppBucket', {
      bucketName: `pbhub-${config.env}`,
      encryption: BucketEncryption.S3_MANAGED,
      versioned: config.bucketVersioning,
      enforceSSL: true,
      removalPolicy,
      autoDeleteObjects: config.removalPolicy === 'destroy',
      // Disable object ACLs entirely; we manage access via bucket policy + presigned URLs.
      objectOwnership: ObjectOwnership.BUCKET_OWNER_ENFORCED,
      // Block public ACLs but allow a public bucket policy (needed for `public/*` prefix).
      blockPublicAccess: new BlockPublicAccess({
        blockPublicAcls: true,
        ignorePublicAcls: true,
        blockPublicPolicy: false,
        restrictPublicBuckets: false,
      }),
      cors: [
        {
          allowedOrigins: config.webOrigins,
          allowedMethods: [
            HttpMethods.GET,
            HttpMethods.PUT,
            HttpMethods.POST,
            HttpMethods.HEAD,
          ],
          allowedHeaders: ['*'],
          exposedHeaders: ['ETag'],
          maxAge: 3000,
        },
      ],
      lifecycleRules: [
        // Private uploads: prune old non-current versions after 90 days
        {
          id: 'prune-old-private-versions',
          prefix: 'private/',
          enabled: true,
          noncurrentVersionExpiration: Duration.days(90),
          abortIncompleteMultipartUploadAfter: Duration.days(7),
        },
        // Cache: delete payslips after 30 days, they're regenerable
        {
          id: 'expire-payslip-cache',
          prefix: 'cache/',
          enabled: true,
          expiration: Duration.days(30),
          abortIncompleteMultipartUploadAfter: Duration.days(7),
        },
        // Long-lived documents → Standard-IA after 1 year, Glacier IR after 3 years
        {
          id: 'tier-employee-docs',
          prefix: 'private/employee-docs/',
          enabled: true,
          transitions: [
            { storageClass: StorageClass.INFREQUENT_ACCESS, transitionAfter: Duration.days(365) },
            { storageClass: StorageClass.GLACIER_INSTANT_RETRIEVAL, transitionAfter: Duration.days(1095) },
          ],
        },
      ],
    });

    // Public read on `public/*` only — branding assets fetched from the unauthenticated login screen.
    this.bucket.addToResourcePolicy(
      new PolicyStatement({
        effect: Effect.ALLOW,
        principals: [new AnyPrincipal()],
        actions: ['s3:GetObject'],
        resources: [`${this.bucket.bucketArn}/public/*`],
      }),
    );

    // IAM user the API (in ECS or wherever) assumes to sign URLs and finalize uploads.
    // For local dev, generate access keys after deploy and put them in the api .env.
    // For prod (ECS/Beanstalk), prefer task role over a long-lived user — we'll add
    // that role in compute-stack.ts later and remove this user in prod.
    this.appUser = new User(this, 'AppUser', {
      userName: `pbhub-app-${config.env}`,
    });

    this.appUser.addManagedPolicy(
      new ManagedPolicy(this, 'AppUserBucketPolicy', {
        statements: [
          new PolicyStatement({
            effect: Effect.ALLOW,
            actions: [
              's3:PutObject',
              's3:PutObjectAcl',
              's3:GetObject',
              's3:DeleteObject',
              's3:AbortMultipartUpload',
              's3:ListMultipartUploadParts',
            ],
            resources: [`${this.bucket.bucketArn}/*`],
          }),
          new PolicyStatement({
            effect: Effect.ALLOW,
            actions: ['s3:ListBucket', 's3:GetBucketLocation'],
            resources: [this.bucket.bucketArn],
          }),
        ],
      }),
    );

    // Outputs — referenced by api .env
    new CfnOutput(this, 'BucketName', {
      value: this.bucket.bucketName,
      description: 'Set as STORAGE_S3_BUCKET in api .env',
      exportName: `pbhub-${config.env}-bucket-name`,
    });
    new CfnOutput(this, 'BucketRegion', {
      value: this.region,
      description: 'Set as STORAGE_S3_REGION in api .env',
      exportName: `pbhub-${config.env}-bucket-region`,
    });
    new CfnOutput(this, 'AppUserArn', {
      value: this.appUser.userArn,
      description: 'IAM user ARN; create access keys via AWS console after deploy',
      exportName: `pbhub-${config.env}-app-user-arn`,
    });
  }
}
